Update setup.py
Update Appium-Python-Client dependency.
The Appium-Python-Client broke somewhere in between e.g. v0.10-v0.13 weren't working anymore with the `set_network_connection_status(self, connectionStatus)` KW. The `connectionStatus` was changed into Enumeration in the `appium.webdriver.WebDriver.set_network_connection(self, connectionType)` which caused `AttributeError: 'int' object has no attribute 'value'` errors when calling it with an integer. This is now corrected in Appium-Python-Client v0.20, which is available in pip.